# Site settings
title: Xin Jin`s Homepage
# baseurl:
url: "https://jinxins.github.io"
# google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Xin Jin (金 鑫)
  desc: Hello nice to meet you
  email: Jinxin20001118@163.com
  selfie: assets/img/xinjin.jpg

# social
social:
  email: ture
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: https://github.com/JinXins
  google_scholar: https://scholar.google.com/citations?user=v3OwxWIAAAAJ&hl=zh-CN
  google_plus:
  instagram:
  keybase:
  # linkedin: https://www.linkedin.com/in/kssim/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: https://twitter.com/Xander_K1ng
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  # - "screenshot.png"
